apiVersion: v1
kind: Service
metadata:
  name: springboot-demo
  namespace: default
  labels:
    app: springboot-demo
spec:
  type: NodePort
  ports:
  - port: 8881
    nodePort: 30090 #service对外开放端口
  selector:
    app: springboot-demo
---
apiVersion: apps/v1
kind: Deployment #对象类型
metadata:
  name: springboot-demo #名称
  labels:
    app: springboot-demo #标注 
spec:
  replicas: 3 #运行容器的副本数，修改这里可以快速修改分布式节点数量
  selector:
    matchLabels:
      app: springboot-demo
  template:
    metadata:
      labels:
        app: springboot-demo
    spec:
      containers: #docker容器的配置
      - name: springboot-demo
        image: registry.cn-hangzhou.aliyuncs.com/huangt/springboot-demo:1.0.0-test # pull镜像的地址 ip:prot/dir/images:tag
        imagePullPolicy: IfNotPresent #pull镜像时机，
        ports:
        - containerPort: 8881 #容器对外开放端口
